import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'student-dashboard',
  templateUrl: './student-dashboard.component.html',
  styleUrls: ['./student-dashboard.component.scss'],
})
export class StudentDashboardComponent implements OnInit {
  public titleH3Text41ConfigProperties: any;
  public subtitleText41ConfigProperties: any;
  public supportingText31ConfigProperties: any;
  public button121ConfigProperties: any;
  public card61ConfigProperties: any;
  public subtitleText52ConfigProperties: any;
  public supportingText42ConfigProperties: any;
  public button132ConfigProperties: any;
  public card72ConfigProperties: any;
  public subtitleText74ConfigProperties: any;
  public supportingText53ConfigProperties: any;
  public button143ConfigProperties: any;
  public card83ConfigProperties: any;

  constructor(private router:Router) {}

  ngOnInit() {
    this.titleH3Text41ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d',
        headingTextStyle: 'color-black mt-3',
      },
      isHidden: false,
      propertyName: '2315de9f-3983-4445-ab17-6f45ec39ef14',
      showLabel: false,
      type: 'title-h3-text',
      value: 'Student Dashboard',
      formControlName: 'titleH3Text41FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faH3',
      listChilds: [],
      styleType: '',
      variableName: 'titleH3Text41ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText41ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-weight-600 font-size-12rem',
      },
      isHidden: false,
      propertyName: '466b38de-8043-4842-aed4-ea135a8882a2',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Exams',
      formControlName: 'subtitleText41FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText41ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText31ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d font-size-09rem',
      },
      isHidden: false,
      propertyName: '40572106-cf15-4fa5-9137-85ee4eeb541f',
      showLabel: false,
      type: 'supporting-text',
      value: 'View and give exams',
      formControlName: 'supportingText31FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText31ConfigProperties',
      listOfOptions: [],
    };
    this.button121ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center margin-top-2-percent',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 font-size-09rem font-weight-600 color-rgb255-255-255-1 background-color-rgb74-21-72-1',
      },
      isHidden: false,
      propertyName: '209b9270-16f9-41d6-88a6-a76e2b7c363e',
      showLabel: false,
      type: 'button',
      formControlName: 'button121FormControl',
      btnText: 'Go To Exams',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button121ConfigProperties',
      listOfOptions: [],
    };
    this.card61ConfigProperties = {
      helpText: '',
      styles: {
        supportingTextStyle: 'color-6c757d',
        cardComponentStyle: 'height-50 margin-left-5rem margin-right-5rem',
        cardBodyStyle:
          'border-width-1 border-style-solid border-color-000000 border-radius-05rem box-shadow-0-20-25--5-rgb0-0-0--01-0-8-10--6-rgb0-0-0--01 p-3',
      },
      isHidden: false,
      propertyName: 'd70c56c6-b5e9-4ca4-95d2-27e2ff522818',
      showLabel: false,
      type: 'card',
      formControlName: 'card61FormControl',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [
        {
          componentId: 16,
          componentName: 'Subtitle Text 4 1',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: '466b38de-8043-4842-aed4-ea135a8882a2',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1020101010,
          value: 'Exams',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'black', fontWeight: '600', fontSize: '1.2rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 1,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 0,
        },
        {
          componentId: 19,
          componentName: 'Supporting Text 3 1',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faFont',
          componentType: 'Text',
          showLabel: false,
          propertyName: '40572106-cf15-4fa5-9137-85ee4eeb541f',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'supporting-text',
          sortOrder: 1020101020,
          value: 'View and give exams',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d', fontSize: '0.9rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 2,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 1,
        },
        {
          componentId: 9,
          componentName: 'Button 12 1',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faRectangleLandscape',
          componentType: 'Basic Input Fields',
          showLabel: false,
          propertyName: '209b9270-16f9-41d6-88a6-a76e2b7c363e',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'button',
          sortOrder: 1020101030,
          btnClass: 'btn-primary',
          btnText: 'Go To Exams',
          value: null,
          isActive: false,
          btnType: 'button',
          dynamicFn: [],
          staticFn: [],
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center', marginTop: '2%' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 17,
              styleType: 'button-styles',
              styleObj: {
                borderRadius: '4px',
                borderWidth: '1px',
                fontSize: '0.9rem',
                fontWeight: '600',
                color: 'rgb(255, 255, 255, 1)',
                bgColor: 'rgb(74, 21, 72, 1)',
              },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles', 'button-styles'],
          allowApiConfiguration: true,
          formControlName: '',
          templatePropertyId: 3,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 2,
        },
      ],
      icon: 'faIdCard',
      listChilds: [],
      styleType: '',
      variableName: 'card61ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText52ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-12rem font-weight-600',
      },
      isHidden: false,
      propertyName: '8080bb89-526c-4892-aff1-60627def4e2c',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Results',
      formControlName: 'subtitleText52FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText52ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText42ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d font-size-09rem',
      },
      isHidden: false,
      propertyName: 'af1fd6e4-003e-47d6-bb7f-9af35ca5118e',
      showLabel: false,
      type: 'supporting-text',
      value: 'View your all the results',
      formControlName: 'supportingText42FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText42ConfigProperties',
      listOfOptions: [],
    };
    this.button132ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center margin-top-2-percent',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 font-size-09rem font-weight-600 color-rgb255-255-255-1 background-color-rgb74-21-72-1',
      },
      isHidden: false,
      propertyName: '23d81f07-0c27-4d07-aea2-bdd4ae015f96',
      showLabel: false,
      type: 'button',
      formControlName: 'button132FormControl',
      btnText: 'Go To Results',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button132ConfigProperties',
      listOfOptions: [],
    };
    this.card72ConfigProperties = {
      helpText: '',
      styles: {
        supportingTextStyle: 'color-6c757d',
        cardComponentStyle: 'height-50 margin-left-5rem margin-right-5rem',
        cardBodyStyle:
          'border-width-1 border-style-solid border-color-000000 border-radius-05rem box-shadow-0-20-25--5-rgb0-0-0--01-0-8-10--6-rgb0-0-0--01 p-3',
      },
      isHidden: false,
      propertyName: 'fefdb633-b679-48a1-990c-94fe41dd8ae1',
      showLabel: false,
      type: 'card',
      formControlName: 'card72FormControl',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [
        {
          componentId: 16,
          componentName: 'Subtitle Text 5 2',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: '8080bb89-526c-4892-aff1-60627def4e2c',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1020201010,
          value: 'Results',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'black', fontSize: '1.2rem', fontWeight: '600' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 1,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 0,
        },
        {
          componentId: 19,
          componentName: 'Supporting Text 4 2',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faFont',
          componentType: 'Text',
          showLabel: false,
          propertyName: 'af1fd6e4-003e-47d6-bb7f-9af35ca5118e',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'supporting-text',
          sortOrder: 1020201020,
          value: 'View your all the results',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d', fontSize: '0.9rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 2,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 1,
        },
        {
          componentId: 9,
          componentName: 'Button 13 2',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faRectangleLandscape',
          componentType: 'Basic Input Fields',
          showLabel: false,
          propertyName: '23d81f07-0c27-4d07-aea2-bdd4ae015f96',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'button',
          sortOrder: 1020201030,
          btnClass: 'btn-primary',
          btnText: 'Go To Results',
          value: null,
          isActive: false,
          btnType: 'button',
          dynamicFn: [],
          staticFn: [],
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center', marginTop: '2%' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 17,
              styleType: 'button-styles',
              styleObj: {
                borderRadius: '4px',
                borderWidth: '1px',
                fontSize: '0.9rem',
                fontWeight: '600',
                color: 'rgb(255, 255, 255, 1)',
                bgColor: 'rgb(74, 21, 72, 1)',
              },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles', 'button-styles'],
          allowApiConfiguration: true,
          formControlName: '',
          templatePropertyId: 3,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 2,
        },
      ],
      icon: 'faIdCard',
      listChilds: [],
      styleType: '',
      variableName: 'card72ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText74ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-12rem font-weight-600',
      },
      isHidden: false,
      propertyName: '3c00a9e1-af8a-4206-8eb1-e30eefb86bf8',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Profile',
      formControlName: 'subtitleText74FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText74ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText53ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center',
        supportingTextStyle: 'color-6c757d font-size-09rem',
      },
      isHidden: false,
      propertyName: 'a7d8910a-f8c0-4428-8d9f-219c859dd22a',
      showLabel: false,
      type: 'supporting-text',
      value: 'View your profile',
      formControlName: 'supportingText53FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText53ConfigProperties',
      listOfOptions: [],
    };
    this.button143ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-center margin-top-2-percent',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 font-size-09rem font-weight-600 color-rgb255-255-255-1 background-color-rgb74-21-72-1',
      },
      isHidden: false,
      propertyName: '8c86f896-5f54-4095-ac42-0ced24515c29',
      showLabel: false,
      type: 'button',
      formControlName: 'button143FormControl',
      btnText: 'Go To Profile',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button143ConfigProperties',
      listOfOptions: [],
    };
    this.card83ConfigProperties = {
      helpText: '',
      styles: {
        supportingTextStyle: 'color-6c757d',
        cardComponentStyle: 'height-50 margin-left-5rem margin-right-5rem',
        cardBodyStyle:
          'border-width-1 border-style-solid border-color-000000 border-radius-05rem box-shadow-0-20-25--5-rgb0-0-0--01-0-8-10--6-rgb0-0-0--01 p-3',
      },
      isHidden: false,
      propertyName: '3246050a-ad1d-4bdb-ab6b-8c7726275af5',
      showLabel: false,
      type: 'card',
      formControlName: 'card83FormControl',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [
        {
          componentId: 16,
          componentName: 'Subtitle Text 7 4',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: '3c00a9e1-af8a-4206-8eb1-e30eefb86bf8',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1020301010,
          value: 'Profile',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'black', fontSize: '1.2rem', fontWeight: '600' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 1,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 0,
        },
        {
          componentId: 19,
          componentName: 'Supporting Text 5 3',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faFont',
          componentType: 'Text',
          showLabel: false,
          propertyName: 'a7d8910a-f8c0-4428-8d9f-219c859dd22a',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'supporting-text',
          sortOrder: 1020301020,
          value: 'View your profile',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d', fontSize: '0.9rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 2,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 1,
        },
        {
          componentId: 9,
          componentName: 'Button 14 3',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faRectangleLandscape',
          componentType: 'Basic Input Fields',
          showLabel: false,
          propertyName: '8c86f896-5f54-4095-ac42-0ced24515c29',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'button',
          sortOrder: 1020301030,
          btnClass: 'btn-primary',
          btnText: 'Go To Profile',
          value: null,
          isActive: false,
          btnType: 'button',
          dynamicFn: [],
          staticFn: [],
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { textAlign: 'center', marginTop: '2%' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 17,
              styleType: 'button-styles',
              styleObj: {
                borderRadius: '4px',
                borderWidth: '1px',
                fontSize: '0.9rem',
                fontWeight: '600',
                color: 'rgb(255, 255, 255, 1)',
                bgColor: 'rgb(74, 21, 72, 1)',
              },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles', 'button-styles'],
          allowApiConfiguration: true,
          formControlName: '',
          templatePropertyId: 3,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 2,
        },
      ],
      icon: 'faIdCard',
      listChilds: [],
      styleType: '',
      variableName: 'card83ConfigProperties',
      listOfOptions: [],
    };
  }

  button121submitForm() {
    this.router.navigate(['/exams'])
  }
  card61Clicked() {}
  button132submitForm() {
    this.router.navigate(['/exam-history'])
  }
  card72Clicked() {}
  button143submitForm() {}
  card83Clicked() {}
}
