import { Component, OnInit, TemplateRef, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';
import { ExamService } from 'src/app/Service/exam.service';


@Component({
  selector: 'upcoming-exams',
  templateUrl: './upcoming-exams.component.html',
  styleUrls: ['./upcoming-exams.component.scss']
})
export class UpcomingExamsComponent implements OnInit {
  public titleH3Text12ConfigProperties: any;
  public subtitleText45ConfigProperties: any;
  public supportingText1ConfigProperties: any;
  public supportingText34ConfigProperties: any;
  public subtitleText67ConfigProperties: any;
  public supportingText45ConfigProperties: any;
  public subtitleText78ConfigProperties: any;
  public supportingText56ConfigProperties: any;
  public subtitleText89ConfigProperties: any;
  public supportingText67ConfigProperties: any;
  public subtitleText910ConfigProperties: any;
  public button1ConfigProperties: any;
  public card1ConfigProperties: any;
  public popup8ConfigProperties: any;
  @ViewChild('popup8Template') popup8Template!: TemplateRef<any>;
  popup8BsModalRef!: BsModalRef;
  public subtitleText454ConfigProperties: any;
  public subtitleText476ConfigProperties: any;
  public subtitleText487ConfigProperties: any;
  public list11ConfigProperties: any;
  public button111ConfigProperties: any;
  public exams : any[]=[];
  public cardsConfigProperties: any[]=[];
  public button1BsModalRef: any;
  public button1Template: any;
  public selectedExam :any;
  public userExamId:any;

  constructor(public modalService: BsModalService, private examService: ExamService, private router: Router) {}

  ngOnInit() {
   this.getAllExams();
   this.initializeConfigProperties();
  //  this.updateConfigProperties(); 
  }

  private initializeConfigProperties(){
    this.titleH3Text12ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        headingTextStyle: 'color-black margin-top-5rem font-weight-600',
      },
      isHidden: false,
      propertyName: '55ee05f8-04b8-4012-901a-e481da9db64d',
      showLabel: false,
      type: 'title-h3-text',
      value: 'Upcoming Exams',
      formControlName: 'titleH3Text12FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faH3',
      listChilds: [],
      styleType: '',
      variableName: 'titleH3Text12ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText45ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-weight-600',
      },
      isHidden: false,
      propertyName: 'f3baaf72-daee-4d7f-956a-e737656de28b',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Angular',
      formControlName: 'subtitleText45FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText45ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText1ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-rgb0-0-0-1 font-weight-600 font-size-08rem',
      },
      isHidden: false,
      propertyName: 'ecc723f6-ffd4-406c-bb8b-531196474782',
      showLabel: false,
      type: 'supporting-text',
      value: 'Test',
      formControlName: 'supportingText1FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText1ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText34ConfigProperties = {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: 'cfc076a2-5c79-4484-9856-3912f8244591',
      showLabel: false,
      type: 'supporting-text',
      value: 'Start Date',
      formControlName: 'supportingText34FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText34ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText67ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem'
      },
      isHidden: false,
      propertyName: '187b05d9-aa51-431a-ba31-eeb9593cbaa2',
      showLabel: false,
      type: 'subtitle-text',
      value: 'November 22, 2024',
      formControlName: 'subtitleText67FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText67ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText45ConfigProperties = {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: '9e6730c0-e348-44c4-89a5-ef7efcd3b20f',
      showLabel: false,
      type: 'supporting-text',
      value: 'End Date',
      formControlName: 'supportingText45FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText45ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText78ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: '3cf3e9b3-7730-48a8-9480-b7652e178dd0',
      showLabel: false,
      type: 'subtitle-text',
      value: 'November 24, 2024',
      formControlName: 'subtitleText78FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText78ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText56ConfigProperties = {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: '66f299f6-da1f-444d-98de-0e1e4779410e',
      showLabel: false,
      type: 'supporting-text',
      value: 'Duration',
      formControlName: 'supportingText56FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText56ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText89ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: 'a76d7e66-6954-49f0-a80f-bbd4db995d69',
      showLabel: false,
      type: 'subtitle-text',
      value: '30 nimutes',
      formControlName: 'subtitleText89FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText89ConfigProperties',
      listOfOptions: [],
    };
    this.supportingText67ConfigProperties = {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: 'db99ca31-7f6e-4930-8fbc-63905eec8984',
      showLabel: false,
      type: 'supporting-text',
      value: 'Passing Marks',
      formControlName: 'supportingText67FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText67ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText910ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: '4445ba7a-277b-40e3-9318-90cf6af8d9ac',
      showLabel: false,
      type: 'subtitle-text',
      value: '50',
      formControlName: 'subtitleText910FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText910ConfigProperties',
      listOfOptions: [],
    };
    this.button1ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'position-relative text-align-center m-1',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 width-100-percent background-color-rgb223-65-4-1 font-size-16 font-weight-400 color-rgb255-255-255-1 m-1 p-1',
      },
      isHidden: false,
      propertyName: '46cc7ef4-4443-40e7-8e4a-3a303bdd5620',
      showLabel: false,
      type: 'button',
      formControlName: 'button1FormControl',
      btnText: 'Take Exam',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button1ConfigProperties',
      listOfOptions: [],
    };
    this.card1ConfigProperties = {
      helpText: '',
      styles: {
        supportingTextStyle: 'color-6c757d',
        cardComponentStyle: 'height-50 margin-top-3rem width-50-percent',
        cardBodyStyle:
          'box-shadow-0-20-25--5-rgb0-0-0--01-0-8-10--6-rgb0-0-0--01 border-style-dotted border-color-rgb130-130-130-1 border-radius-05rem border-width-0005rem p-1',
      },
      isHidden: false,
      propertyName: '12ec0734-328a-4812-944e-b4dd0f49b027',
      showLabel: false,
      type: 'card',
      formControlName: 'card1FormControl',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      icon: 'faClone',
      listChilds: [],
      styleType: '',
      variableName: 'popup8ConfigProperties',
      listOfOptions: [],
      modalTitle: 'Exam Instructions:',
      childs:[
        {
          componentId: 16,
          componentName: 'Subtitle Text 4 5',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: 'f3baaf72-daee-4d7f-956a-e737656de28b',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1010202010,
          value: 'Angular',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'black', fontWeight: '600' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 1,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 0,
        },
        {
          componentId: 19,
          componentName: 'Supporting Text 1',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faFont',
          componentType: 'Text',
          showLabel: false,
          propertyName: 'ecc723f6-ffd4-406c-bb8b-531196474782',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'supporting-text',
          sortOrder: 1010202020,
          value: 'Test',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: 'rgb(0, 0, 0, 1)', fontWeight: '600', fontSize: '0.8rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 2,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 1,
        },
        {
          componentId: 28,
          displayName: 'Grid',
          componentName: 'Grid 6 6',
          childs: [],
          icon: 'faGrid',
          componentType: 'layouts',
          showLabel: false,
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'grid',
          sortOrder: 1010202030,
          gridColsChild: [
            {
              displayName: 'Column-0',
              componentId: 280,
              componentKey: 'grid',
              type: 'grid_col',
              propertyType: 'string',
              componentType: 'layouts',
              controlType: 'string',
              propertyName: '28b5c341-0c05-4b45-ac20-38fc7d626b25_G_Col_0',
              hasChildEntity: true,
              hasPlaceholder: false,
              hasDefaultValue: false,
              sortOrder: 101020203010,
              showLabel: false,
              validations: [],
              validationsList: [],
              childs: [
                {
                  componentId: 19,
                  componentName: 'Supporting Text 3 4',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faFont',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: 'cfc076a2-5c79-4484-9856-3912f8244591',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'supporting-text',
                  sortOrder: 10102020301010,
                  value: 'Sart Date',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d', fontSize: '0.8rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 1,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 0,
                },
                {
                  componentId: 16,
                  componentName: 'Subtitle Text 6 7',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faText',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: '187b05d9-aa51-431a-ba31-eeb9593cbaa2',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'subtitle-text',
                  sortOrder: 10102020301020,
                  value: 'November 22, 2024',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 16,
                      styleType: 'subtitle-text-styles',
                      styleObj: { color: 'black', fontSize: '0.9rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: [
                    'component-styles',
                    'subtitle-text-styles',
                    'supporting-text-styles',
                  ],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 2,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 1,
                },
              ],
              colSize: 'col-lg-6',
              isActive: false,
              styles: {},
              customStyles: [
                {
                  title: 'Grid Column Styles',
                  value: 'grid-col-styles',
                  styleId: 6,
                  styleObj: { color: 'black' },
                  customCssClasses: [],
                  flexAlignmentClasses: [],
                  supportedStyleIds: [1, 3, 4, 5, 6, 8, 10, 11],
                },
              ],
              customStyleTypeOptions: ['grid-col-styles'],
              componentName: 'Column-0',
              isDataStoredInSession: false,
              fieldStorageKeyValue: '',
              mapValuesFromProperty: '',
              isHidden: false,
              templatePropertyId: 101020203010,
              index: 0,
            },
            {
              displayName: 'Column-1',
              componentId: 281,
              componentKey: 'grid',
              type: 'grid_col',
              propertyType: 'string',
              componentType: 'layouts',
              controlType: 'string',
              propertyName: '28b5c341-0c05-4b45-ac20-38fc7d626b25_G_Col_1',
              hasChildEntity: true,
              hasPlaceholder: false,
              hasDefaultValue: false,
              sortOrder: 101020203020,
              showLabel: false,
              validations: [],
              validationsList: [],
              childs: [
                {
                  componentId: 19,
                  componentName: 'Supporting Text 4 5',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faFont',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: '9e6730c0-e348-44c4-89a5-ef7efcd3b20f',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'supporting-text',
                  sortOrder: 10102020302010,
                  value: 'End Date',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d', fontSize: '0.8rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 1,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 0,
                },
                {
                  componentId: 16,
                  componentName: 'Subtitle Text 7 8',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faText',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: '3cf3e9b3-7730-48a8-9480-b7652e178dd0',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'subtitle-text',
                  sortOrder: 10102020302020,
                  value: 'November 24, 2024',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 16,
                      styleType: 'subtitle-text-styles',
                      styleObj: { color: 'black', fontSize: '0.9rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: [
                    'component-styles',
                    'subtitle-text-styles',
                    'supporting-text-styles',
                  ],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 2,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 1,
                },
              ],
              colSize: 'col-lg-6',
              isActive: false,
              styles: {},
              customStyles: [
                {
                  title: 'Grid Column Styles',
                  value: 'grid-col-styles',
                  styleId: 6,
                  styleObj: { color: 'black' },
                  customCssClasses: [],
                  flexAlignmentClasses: [],
                  supportedStyleIds: [1, 3, 4, 5, 6, 8, 10, 11],
                },
              ],
              customStyleTypeOptions: ['grid-col-styles'],
              componentName: 'Column-1',
              isDataStoredInSession: false,
              fieldStorageKeyValue: '',
              mapValuesFromProperty: '',
              isHidden: false,
              templatePropertyId: 101020203020,
              index: 1,
            },
          ],
          isActive: false,
          dynamicFn: [],
          isElementLooped: false,
          iterationKey: '',
          note: '',
          styles: {},
          customStyles: [
            {
              styleId: 5,
              styleType: 'grid-styles',
              styleObj: { marginTop: '1rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['grid-styles'],
          allowApiConfiguration: false,
          propertyName: '28b5c341-0c05-4b45-ac20-38fc7d626b25',
          templatePropertyId: 3,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          isHidden: false,
          customCssClasses: [],
          defaultState: '',
          index: 2,
        },
        {
          componentId: 28,
          displayName: 'Grid',
          componentName: 'Grid 7 7',
          childs: [],
          icon: 'faGrid',
          componentType: 'layouts',
          showLabel: false,
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'grid',
          sortOrder: 1010202040,
          gridColsChild: [
            {
              displayName: 'Column-0',
              componentId: 280,
              componentKey: 'grid',
              type: 'grid_col',
              propertyType: 'string',
              componentType: 'layouts',
              controlType: 'string',
              propertyName: '2baae4bb-4b1a-4aef-ba4c-e6dfa472ca4d_G_Col_0',
              hasChildEntity: true,
              hasPlaceholder: false,
              hasDefaultValue: false,
              sortOrder: 101020204010,
              showLabel: true,
              validations: [],
              validationsList: [],
              childs: [
                {
                  componentId: 19,
                  componentName: 'Supporting Text 5 6',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faFont',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: '66f299f6-da1f-444d-98de-0e1e4779410e',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'supporting-text',
                  sortOrder: 10102020401010,
                  value: 'Duration',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d', fontSize: '0.8rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 1,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 0,
                },
                {
                  componentId: 16,
                  componentName: 'Subtitle Text 8 9',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faText',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: 'a76d7e66-6954-49f0-a80f-bbd4db995d69',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'subtitle-text',
                  sortOrder: 10102020401020,
                  value: '30 nimutes',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 16,
                      styleType: 'subtitle-text-styles',
                      styleObj: { color: 'black', fontSize: '0.9rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: [
                    'component-styles',
                    'subtitle-text-styles',
                    'supporting-text-styles',
                  ],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 2,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 1,
                },
              ],
              colSize: 'col-lg-6',
              isActive: false,
              styles: {},
              customStyles: [
                {
                  title: 'Grid Column Styles',
                  value: 'grid-col-styles',
                  styleId: 6,
                  styleObj: { color: 'black' },
                  customCssClasses: [],
                  flexAlignmentClasses: [],
                  supportedStyleIds: [1, 3, 4, 5, 6, 8, 10, 11],
                },
              ],
              customStyleTypeOptions: ['grid-col-styles'],
              templatePropertyId: 101020204010,
              index: 0,
            },
            {
              displayName: 'Column-1',
              componentId: 281,
              componentKey: 'grid',
              type: 'grid_col',
              propertyType: 'string',
              componentType: 'layouts',
              controlType: 'string',
              propertyName: '2baae4bb-4b1a-4aef-ba4c-e6dfa472ca4d_G_Col_1',
              hasChildEntity: true,
              hasPlaceholder: false,
              hasDefaultValue: false,
              sortOrder: 101020204020,
              showLabel: true,
              validations: [],
              validationsList: [],
              childs: [
                {
                  componentId: 19,
                  componentName: 'Supporting Text 6 7',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faFont',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: 'db99ca31-7f6e-4930-8fbc-63905eec8984',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'supporting-text',
                  sortOrder: 10102020402010,
                  value: 'Passing Marks',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d', fontSize: '0.8rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: ['component-styles', 'supporting-text-styles'],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 1,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 0,
                },
                {
                  componentId: 16,
                  componentName: 'Subtitle Text 9 10',
                  listChilds: [],
                  styleType: '',
                  mobileFloatAlignment: '',
                  childs: [],
                  icon: 'faText',
                  componentType: 'Text',
                  showLabel: false,
                  propertyName: '4445ba7a-277b-40e3-9318-90cf6af8d9ac',
                  newProperty: true,
                  hasChildEntity: false,
                  hasPlaceholder: false,
                  type: 'subtitle-text',
                  sortOrder: 10102020402020,
                  value: '50',
                  isActive: false,
                  customCssClasses: [],
                  note: '',
                  isHidden: false,
                  isImplemented: true,
                  styles: {},
                  labelStyles: {},
                  helpText: '',
                  navigateTo: '',
                  listOfOptions: [],
                  customStyles: [
                    {
                      styleId: 1,
                      styleType: 'component-styles',
                      styleObj: {},
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 4,
                      styleType: 'supporting-text-styles',
                      styleObj: { color: '#6c757d' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                    {
                      styleId: 16,
                      styleType: 'subtitle-text-styles',
                      styleObj: { color: 'black', fontSize: '0.9rem' },
                      customCssClasses: [],
                      flexAlignmentClasses: [],
                    },
                  ],
                  customStyleTypeOptions: [
                    'component-styles',
                    'subtitle-text-styles',
                    'supporting-text-styles',
                  ],
                  allowApiConfiguration: false,
                  formControlName: '',
                  templatePropertyId: 2,
                  isDataStoredInSession: false,
                  fieldStorageKeyValue: '',
                  mapValuesFromProperty: '',
                  defaultState: '',
                  index: 1,
                },
              ],
              colSize: 'col-lg-6',
              isActive: false,
              styles: {},
              customStyles: [
                {
                  title: 'Grid Column Styles',
                  value: 'grid-col-styles',
                  styleId: 6,
                  styleObj: { color: 'black' },
                  customCssClasses: [],
                  flexAlignmentClasses: [],
                  supportedStyleIds: [1, 3, 4, 5, 6, 8, 10, 11],
                },
              ],
              customStyleTypeOptions: ['grid-col-styles'],
              customCssClasses: [],
              defaultState: '',
              templatePropertyId: 101020204020,
              index: 1,
            },
          ],
          isActive: false,
          dynamicFn: [],
          isElementLooped: false,
          iterationKey: '',
          note: '',
          styles: {},
          customStyles: [
            {
              styleId: 5,
              styleType: 'grid-styles',
              styleObj: { marginTop: '1rem' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['grid-styles'],
          allowApiConfiguration: false,
          propertyName: '2baae4bb-4b1a-4aef-ba4c-e6dfa472ca4d',
          templatePropertyId: 4,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          isHidden: false,
          customCssClasses: [],
          defaultState: '',
          index: 3,
        },
        {
          componentId: 9,
          componentName: 'Button 1',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faRectangleLandscape',
          componentType: 'Basic Input Fields',
          showLabel: false,
          propertyName: '46cc7ef4-4443-40e7-8e4a-3a303bdd5620',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'button',
          sortOrder: 1010202050,
          btnClass: 'btn-primary',
          btnText: 'Take Exam',
          value: null,
          isActive: false,
          btnType: 'button',
          dynamicFn: [],
          staticFn: [],
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { position: 'relative', textAlign: 'center' },
              customCssClasses: ['m-1'],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 17,
              styleType: 'button-styles',
              styleObj: {
                borderRadius: '4px',
                borderWidth: '1px',
                width: '100%',
                bgColor: 'rgb(223, 65, 4, 1)',
                fontSize: '16px',
                fontWeight: '400',
                color: 'rgb(255, 255, 255, 1)',
              },
              customCssClasses: ['m-1', 'p-1'],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles', 'button-styles'],
          allowApiConfiguration: true,
          formControlName: '',
          templatePropertyId: 5,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 4,
        },
      ]
    };
    this.subtitleText454ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-weight-600 font-size-11rem',
      },
      isHidden: false,
      propertyName: '622b660d-84c4-4fc3-890b-0969851a43c6',
      showLabel: false,
      type: 'subtitle-text',
      value: 'You have 30 Minutes to answer the questions',
      formControlName: 'subtitleText454FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText454ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText476ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '9d4a3f9e-3dbb-4496-a886-ca975507668c',
      showLabel: false,
      type: 'subtitle-text',
      value: 'The test include multiple choice questions',
      formControlName: 'subtitleText476FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText476ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText487ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'margin-top-2rem',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-weight-600',
      },
      isHidden: false,
      propertyName: 'b3427cbb-6c3f-49fb-a50c-6081bbb1cd81',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Before you start:',
      formControlName: 'subtitleText487FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText487ConfigProperties',
      listOfOptions: [],
    };
    this.list11ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-rgb130-130-130-1',
        listStyle: 'color-black',
      },
      isHidden: false,
      propertyName: 'd9efbe36-f3ce-4b6c-b5f6-6c60129e2c5e',
      showLabel: false,
      type: 'list',
      value: 'circle',
      formControlName: 'list11FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faList',
      dropDisplayName: '',
      listChilds: [
        'Make sure your internet is reliable, you have to complete this test in one session.',
        'You can move between the questions',
        'Youcan go back and change your answers  before submitting the test',
      ],
      styleType: '',
      variableName: 'list11ConfigProperties',
      listOfOptions: [],
    };
    this.button111ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'text-align-right',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 font-size-16 font-weight-400 color-rgb255-255-255-1 background-color-rgb74-21-72-1',
      },
      isHidden: false,
      propertyName: '43f75186-b31e-47a7-aaba-df093dd0b6c4',
      showLabel: false,
      type: 'button',
      formControlName: 'button111FormControl',
      btnText: 'Start Exam',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button111ConfigProperties',
      listOfOptions: [],
    };
  }

  private updateConfigProperties():void{
    console.log(this.exams)
    this.cardsConfigProperties = this.exams.map((exam)=>({
     card1ConfigProperties:{
      helpText: '',
      styles: {
        supportingTextStyle: 'color-6c757d',
        cardComponentStyle: 'height-50 margin-top-3rem width-50-percent',
        cardBodyStyle:
          'box-shadow-0-20-25--5-rgb0-0-0--01-0-8-10--6-rgb0-0-0--01 border-style-dotted border-color-rgb130-130-130-1 border-radius-05rem border-width-0005rem p-1',
      },
      isHidden: false,
      propertyName: exam.examId,
      showLabel: false,
      type: 'card',
      formControlName: `card_${exam.examId}`,
      navigateTo: '',
      staticFn: [],
      customCssClasses: []
     },
     titleH3Text12ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        headingTextStyle: 'color-black margin-top-5rem font-weight-600',
      },
      isHidden: false,
      propertyName: `titleh3_${exam.examId}`,
      showLabel: false,
      type: 'title-h3-text',
      value: 'Upcoming Exams',
      formControlName: `titleH3Text_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faH3',
      listChilds: [],
      styleType: '',
      variableName: 'titleH3Text12ConfigProperties',
      listOfOptions: [],
    },
    subtitleText45ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-weight-600',
      },
      isHidden: false,
      propertyName: `subtitle_${exam.examId}`,
      showLabel: false,
      type: 'subtitle-text',
      value: exam.title,
      formControlName: `subtitleText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText45ConfigProperties',
      listOfOptions: [],
    },
    supportingText1ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-rgb0-0-0-1 font-weight-600 font-size-08rem',
      },
      isHidden: false,
      propertyName: `supporting_${exam.examId}`,
      showLabel: false,
      type: 'supporting-text',
      value: 'Test',
      formControlName: `supportingText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText1ConfigProperties',
      listOfOptions: [],
    },
    supportingText34ConfigProperties :{
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: `supporting_${exam.examId}`,
      showLabel: false,
      type: 'supporting-text',
      value: 'Start Date',
      formControlName: `supportingText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText34ConfigProperties',
      listOfOptions: [],
    },
    subtitleText67ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem'
      },
      isHidden: false,
      propertyName: `subtitle_${exam.examId}`,
      showLabel: false,
      type: 'subtitle-text',
      value: new Date(exam.startDate).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
      formControlName: `subtitleText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText67ConfigProperties',
      listOfOptions: [],
    },
    supportingText45ConfigProperties : {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: `supporting_${exam.examId}`,
      showLabel: false,
      type: 'supporting-text',
      value: 'End Date',
      formControlName: `supportingText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText45ConfigProperties',
      listOfOptions: [],
    },
    subtitleText78ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: `subtitle_${exam.examId}`,
      showLabel: false,
      type: 'subtitle-text',
      value: new Date(exam.endDate).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
      formControlName: `subtitleText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText78ConfigProperties',
      listOfOptions: [],
    },
    supportingText56ConfigProperties : {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: `supporting_${exam.examId}`,
      showLabel: false,
      type: 'supporting-text',
      value: 'Duration',
      formControlName: `supportingText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText56ConfigProperties',
      listOfOptions: [],
    },
    subtitleText89ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: `subtitle_${exam.examId}`,
      showLabel: false,
      type: 'subtitle-text',
      value: `${exam.duration} minutes`,
      formControlName: `subtitleText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText89ConfigProperties',
      listOfOptions: [],
    },
    supportingText67ConfigProperties : {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: `supporting_${exam.examId}`,
      showLabel: false,
      type: 'supporting-text',
      value: 'Passing Marks',
      formControlName: `supportingText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText67ConfigProperties',
      listOfOptions: [],
    },
    subtitleText910ConfigProperties :{
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: `subtitle_${exam.examId}`,
      showLabel: false,
      type: 'subtitle-text',
      value: exam.passingMarks,
      formControlName: `subtitleText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText910ConfigProperties',
      listOfOptions: [],
    },
    supportingText68ConfigProperties : {
      helpText: '',
      styles: { componentStyle: '', supportingTextStyle: 'color-6c757d font-size-08rem' },
      isHidden: false,
      propertyName: `supporting_${exam.examId}`,
      showLabel: false,
      type: 'supporting-text',
      value: 'Total Marks',
      formControlName: `supportingText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faFont',
      listChilds: [],
      styleType: '',
      variableName: 'supportingText67ConfigProperties',
      listOfOptions: [],
    },
    subtitleText911ConfigProperties :{
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-black font-size-09rem',
      },
      isHidden: false,
      propertyName: `subtitle_${exam.examId}`,
      showLabel: false,
      type: 'subtitle-text',
      value: exam.totalMarks,
      formControlName: `subtitleText_${exam.examId}`,
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText910ConfigProperties',
      listOfOptions: [],
    },
  button1ConfigProperties : {
      helpText: '',
      styles: {
        componentStyle: 'position-relative text-align-center m-1',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 width-100-percent background-color-rgb223-65-4-1 font-size-16 font-weight-400 color-rgb255-255-255-1 m-1 p-1',
      },
      isHidden: false,
      propertyName: `${exam.examId}`,
      showLabel: false,
      type: 'button',
      formControlName: `buttonEdit_${exam.examId}`,
      btnText: 'Take Exam',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button1ConfigProperties',
      listOfOptions: [],
    }
    }))
    console.log(this.cardsConfigProperties)
  }

  button1submitForm(examId:any) {
    console.log(examId)
    this.getExamByExamId(examId)
    this.router.navigate(['/exam-questions'], { queryParams: { examId: examId } })
  }
  card1Clicked() {}
  list11Changed(event: any) {
    this.list11ConfigProperties = event;
  }
  button111submitForm() {}

  getAllExams(){
  this.examService.GetAllExams().subscribe({
   next:(response)=>{    
      this.exams = response.data
      console.log(this.exams)
      this.updateConfigProperties();
    },
    error: (error)=>{
      console.error('Error in fetching exams for student:', error)
    }
  })
  }

  getExamByExamId(examId:any){
    this.examService.GetExamByExamId(examId).subscribe({
      next:(response)=>{
        this.selectedExam = response.data
        // return this.selectedExam;
        const payload={
          userId:localStorage.getItem('currentUserId'),
          examId: this.selectedExam.examId,
          startedOn: new Date().toISOString(),
          examStatus: 'Active',
          totalMarks: this.selectedExam.totalMarks,
          isAutoSubmitted: true,
          noOfAttempt: 0,
          createdBy: this.selectedExam.createdBy,
          createdOn: new Date().toISOString(),
          updtedOn: new Date().toISOString()
        }
        this.addToUserExam(payload)
      },
      error:(error)=>{
        console.error('Error in fetching exam details: ', error)
      }
    })
  }

  addToUserExam(payload:any){
    this.examService.AddUserExam(payload).subscribe({
      next:(response)=>{
       this.userExamId= response.data.userExamId
       sessionStorage.setItem('userExam', this.userExamId);
       console.log(this.userExamId)
      },
      error:(error)=>{
        console.error('Error in adding user exam: ', error)
      }
    })
  }
}


