import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserResultService } from 'src/app/Service/user-result.service';

@Component({
  selector: 'exam-history',
  templateUrl: './exam-history.component.html',
  styleUrls: ['./exam-history.component.scss']
})
export class ExamHistoryComponent implements OnInit {
  public titleH3Text21ConfigProperties: any;
  public subtitleText237ConfigProperties: any;
  public subtitleText248ConfigProperties: any;
  public subtitleText259ConfigProperties: any;
  public subtitleText260ConfigProperties: any;
  public subtitleText2610ConfigProperties: any;
  public subtitleText2711ConfigProperties: any;
  public button99ConfigProperties: any;
  public card21ConfigProperties: any;
  public cardConfigProperties:any[]=[]
  public userResults:any[]=[]
  public userId:any;

  constructor(private router: Router, private userResultService: UserResultService) {}

  ngOnInit() {
    this.userId= localStorage.getItem('currentUserId')
    this.getExamResults()
    this.titleH3Text21ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        headingTextStyle: 'color-black font-weight-600 margin-top-5rem decoration-underline',
      },
      isHidden: false,
      propertyName: '6ec6f012-53bb-4507-a77a-a18ba7b4f161',
      showLabel: false,
      type: 'title-h3-text',
      value: 'Exam History',
      formControlName: 'titleH3Text21FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faH3',
      listChilds: [],
      styleType: '',
      variableName: 'titleH3Text21ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText237ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb103-101-101-1 font-size-12rem font-weight-600 ',
      },
      isHidden: false,
      propertyName: 'ffc698e7-078f-4a09-b43a-56120f846ec1',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Angular',
      formControlName: 'subtitleText237FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText237ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText248ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '4e39ebbb-3046-4b5e-bee8-0953bf4ddd07',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Score: 10',
      formControlName: 'subtitleText248FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText248ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText259ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '107bc030-d7e1-440e-a8f7-4e3703b893c2',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Passing Marks: 20',
      formControlName: 'subtitleText259FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText259ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText260ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '107bc030-d7e1-440e-a8f7-4e3703b893c2',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Total Marks: 20',
      formControlName: 'subtitleText259FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText259ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText2610ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: 'bb8beaa6-cd8c-417b-87c4-c053fd28777b',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Status: Fail',
      formControlName: 'subtitleText2610FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText2610ConfigProperties',
      listOfOptions: [],
    };
    this.subtitleText2711ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '1baa05d4-9288-4492-ba03-afaa1f774def',
      showLabel: false,
      type: 'subtitle-text',
      value: 'Result Date:  Nov 21, 2024',
      formControlName: 'subtitleText2711FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText2711ConfigProperties',
      listOfOptions: [],
    };
    this.button99ConfigProperties = {
      helpText: '',
      styles: {
        componentStyle: 'margin-top-5-percent',
        supportingTextStyle: 'color-6c757d',
        buttonStyle:
          'border-radius-4 border-width-1 background-color-rgb74-21-72-1 font-size-16 font-weight-400 color-rgb255-255-255-1 margin-left-1-percent px-2 margin-top-5-percent',
      },
      isHidden: false,
      propertyName: 'ae65213c-a0e9-4dac-aeea-247202d31f1f',
      showLabel: false,
      type: 'button',
      formControlName: 'button99FormControl',
      btnText: 'Show Result',
      btnType: 'button',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [],
      icon: 'faRectangleLandscape',
      listChilds: [],
      styleType: '',
      variableName: 'button99ConfigProperties',
      listOfOptions: [],
    };
    this.card21ConfigProperties = {
      helpText: '',
      styles: {
        supportingTextStyle: 'color-6c757d',
        cardComponentStyle: 'height-50',
        cardBodyStyle:
          'margin-top-2rem box-shadow-0-20-25--5-rgb0-0-0--01-0-8-10--6-rgb0-0-0--01 border-style-dotted border-width-1 border-color-000000 border-radius-08rem p-2 m-3',
      },
      isHidden: false,
      propertyName: 'bf18c6d0-c2a0-479b-a0df-6b04cfd31cb2',
      showLabel: false,
      type: 'card',
      formControlName: 'card21FormControl',
      navigateTo: '',
      staticFn: [],
      customCssClasses: [],
      childs: [
        {
          componentId: 16,
          componentName: 'Subtitle Text 23 7',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: 'ffc698e7-078f-4a09-b43a-56120f846ec1',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1010202010,
          value: 'Angular',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'rgb(103, 101, 101, 1)', fontSize: '1.2rem', fontWeight: '600' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 1,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 0,
        },
        {
          componentId: 16,
          componentName: 'Subtitle Text 24 8',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: '4e39ebbb-3046-4b5e-bee8-0953bf4ddd07',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1010202020,
          value: 'Score: 10',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'rgb(130, 130, 130, 1)' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 2,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 1,
        },
        {
          componentId: 16,
          componentName: 'Subtitle Text 25 9',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: '107bc030-d7e1-440e-a8f7-4e3703b893c2',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1010202030,
          value: 'Passing Marks: 20',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'rgb(130, 130, 130, 1)' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 3,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          index: 2,
        },
        {
          componentId: 16,
          componentName: 'Subtitle Text 26 10',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: 'bb8beaa6-cd8c-417b-87c4-c053fd28777b',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1010202040,
          value: 'Status: Fail',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'rgb(130, 130, 130, 1)' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 4,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          index: 3,
        },
        {
          componentId: 16,
          componentName: 'Subtitle Text 27 11',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faText',
          componentType: 'Text',
          showLabel: false,
          propertyName: '1baa05d4-9288-4492-ba03-afaa1f774def',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'subtitle-text',
          sortOrder: 1010202050,
          value: 'Result Date:  Nov 21, 2024',
          isActive: false,
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: {},
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 16,
              styleType: 'subtitle-text-styles',
              styleObj: { color: 'rgb(130, 130, 130, 1)' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: [
            'component-styles',
            'subtitle-text-styles',
            'supporting-text-styles',
          ],
          allowApiConfiguration: false,
          formControlName: '',
          templatePropertyId: 5,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          index: 4,
        },
        {
          componentId: 9,
          componentName: 'Button 9 9',
          listChilds: [],
          styleType: '',
          mobileFloatAlignment: '',
          childs: [],
          icon: 'faRectangleLandscape',
          componentType: 'Basic Input Fields',
          showLabel: false,
          propertyName: 'ae65213c-a0e9-4dac-aeea-247202d31f1f',
          newProperty: true,
          hasChildEntity: false,
          hasPlaceholder: false,
          type: 'button',
          sortOrder: 1010202060,
          btnClass: 'btn-primary',
          btnText: 'Show Result',
          value: null,
          isActive: false,
          btnType: 'button',
          dynamicFn: [],
          staticFn: [],
          customCssClasses: [],
          note: '',
          isHidden: false,
          isImplemented: true,
          styles: {},
          labelStyles: {},
          helpText: '',
          navigateTo: '',
          listOfOptions: [],
          customStyles: [
            {
              styleId: 1,
              styleType: 'component-styles',
              styleObj: { marginTop: '5%' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 4,
              styleType: 'supporting-text-styles',
              styleObj: { color: '#6c757d' },
              customCssClasses: [],
              flexAlignmentClasses: [],
            },
            {
              styleId: 17,
              styleType: 'button-styles',
              styleObj: {
                borderRadius: '4px',
                borderWidth: '1px',
                bgColor: 'rgb(74, 21, 72, 1)',
                fontSize: '16px',
                fontWeight: '400',
                color: 'rgb(255, 255, 255, 1)',
                marginLeft: '1%',
              },
              customCssClasses: ['p-1'],
              flexAlignmentClasses: [],
            },
          ],
          customStyleTypeOptions: ['component-styles', 'supporting-text-styles', 'button-styles'],
          allowApiConfiguration: true,
          formControlName: '',
          templatePropertyId: 6,
          isDataStoredInSession: false,
          fieldStorageKeyValue: '',
          mapValuesFromProperty: '',
          defaultState: '',
          index: 5,
        },
      ],
      icon: 'faIdCard',
      listChilds: [],
      styleType: '',
      variableName: 'card21ConfigProperties',
      listOfOptions: [],
    };
  }

  updateConfigProperties(){
    this.cardConfigProperties= this.userResults.map((exam)=>({

      subtitleText237ConfigProperties:{
        helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb103-101-101-1 font-size-12rem font-weight-600',
      },
      isHidden: false,
      propertyName: 'ffc698e7-078f-4a09-b43a-56120f846ec1',
      showLabel: false,
      type: 'subtitle-text',
      value: exam.examName,
      formControlName: 'subtitleText237FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText237ConfigProperties',
      listOfOptions: []
      },
      subtitleText248ConfigProperties:{
        helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '4e39ebbb-3046-4b5e-bee8-0953bf4ddd07',
      showLabel: false,
      type: 'subtitle-text',
      value:'Score: '+ exam.obtainedMarks,
      formControlName: 'subtitleText248FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText248ConfigProperties',
      listOfOptions: []
      },
     subtitleText259ConfigProperties:{
        helpText: '',
        styles: {
          componentStyle: '',
          supportingTextStyle: 'color-6c757d',
          subtitleTextStyle: 'color-rgb130-130-130-1',
        },
        isHidden: false,
        propertyName: '107bc030-d7e1-440e-a8f7-4e3703b893c2',
        showLabel: false,
        type: 'subtitle-text',
        value:'Passing Marks: '+ exam.passingMarks,
        formControlName: 'subtitleText259FormControl',
        navigateTo: '',
        customCssClasses: [],
        childs: [],
        icon: 'faText',
        listChilds: [],
        styleType: '',
        variableName: 'subtitleText259ConfigProperties',
        listOfOptions: []
      },
      subtitleText260ConfigProperties:{
        helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '107bc030-d7e1-440e-a8f7-4e3703b893c2',
      showLabel: false,
      type: 'subtitle-text',
      value:'Total Marks: '+ exam.totalMarks,
      formControlName: 'subtitleText259FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText259ConfigProperties',
      listOfOptions: []
      },
      subtitleText2610ConfigProperties:{
        helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: 'bb8beaa6-cd8c-417b-87c4-c053fd28777b',
      showLabel: false,
      type: 'subtitle-text',
      value:'Status: '+exam.resultStatus,
      formControlName: 'subtitleText2610FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText2610ConfigProperties',
      listOfOptions: []
      },
      subtitleText2711ConfigProperties:{
        helpText: '',
      styles: {
        componentStyle: '',
        supportingTextStyle: 'color-6c757d',
        subtitleTextStyle: 'color-rgb130-130-130-1',
      },
      isHidden: false,
      propertyName: '1baa05d4-9288-4492-ba03-afaa1f774def',
      showLabel: false,
      type: 'subtitle-text',
      value:'Result Date: '+ new Date(exam.resultDate).toLocaleDateString('en-US', {
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
      formControlName: 'subtitleText2711FormControl',
      navigateTo: '',
      customCssClasses: [],
      childs: [],
      icon: 'faText',
      listChilds: [],
      styleType: '',
      variableName: 'subtitleText2711ConfigProperties',
      listOfOptions: []
      }
    }))
  }
  

  button99submitForm() {
    this.router.navigate(['/exam-results'])
  }

  getExamResults(){
   this.userResultService.getUserResults(this.userId).subscribe({
    next:(response)=>{
      console.log(response)
     this.userResults= response
     console.log(this.userResults)
     this.updateConfigProperties()
    },
    error:(error)=>{
     error("Error while fetching the user results",error)
    }
   })
  }
  card21Clicked() {}
}
